### ISSUE TITLE
Implement Archiving function

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/mobility-database-interface#144]
**Is your feature request related to a problem? Please describe.**
Datasets should be archived in GCP (Archives).

**Describe the solution you'd like**
Implement Archiving as a cloud function.

**Comment by annaelleduff** [comment]
Was it decided which [type of storage](https://cloud.google.com/storage/pricing#operations-pricing) we would use?

**Comment by LeoFrachet** [comment]
I trust your judgement on those question, I'm going to unassign myself from that task. Ping me if needed (for example if the requested amount is above the already approved 500CAD/month IIRC).

**Comment by maximearmstrong** [comment]
Perfect, thanks!
The retained storage architecture is described below. 

For every source:

Latest version (folder Latest)
- Standard storage on GCS
- A latest dataset version for a source is updated when a newer version is found. The newer version is added and previous one is deleted.

Every version (folder Archives)
- Nearline (0-3 months old), Coldline (3-12) and Archive (12+)
- Every version is stored, including the latest dataset. This avoids unnecessary movements between the Latest and Archives folder when a newer version is found, i.e. the previous latest dataset has not to be moved as it is already in the Archives folder. This simplifies work at a small cost.

**Comment by maximearmstrong** [comment]
Fixed in [Archives Pull#1](https://github.com/MobilityData/mobility-archives-interface/pull/1) and [Archives Pull#3](https://github.com/MobilityData/mobility-archives-interface/pull/3)
