### ISSUE TITLE
Add the Catalog of GTFS Realtime sources (entity) to the Database

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/mobility-database-interface#276]
**Is your feature request related to a problem? Please describe.**
The database must contain a Catalog of GTFS Realtime sources so the harvesting may be done.

**Describe the solution you'd like**
Add the catalog in both the staging (for testing purposes) and the production database.

**Comment by maximearmstrong** [comment]
The [Catalog of GTFS Realtime sources](http://staging.mobilitydatabase.org/wiki/Item:Q22288) was added to the staging with the other items needed.

@LeoFrachet Could you confirm that the data model implemented is correct before it is added to the production database?

- [Catalog of GTFS Realtime sources](http://staging.mobilitydatabase.org/wiki/Item:Q22288)
- [GTFS Realtime data format](http://staging.mobilitydatabase.org/wiki/Item:Q22286)
- [Protobuf](http://staging.mobilitydatabase.org/wiki/Item:Q22287)

**Comment by LeoFrachet** [comment]
Yup, but is there a data model for the GTFS Realtime metadata? I don't remember reading such draft

**Comment by maximearmstrong** [comment]
@LeoFrachet There is no data model for the GTFS Realtime metadata at the moment. This is something we will need to discuss. For now, I am working on the GTFS Realtime MVP (see #282) for the database, which doesn't include the metadata.

**Comment by maximearmstrong** [comment]
The [Catalog of GTFS Realtime sources](http://mobilitydatabase.org/wiki/Item:Q90051) was added to the production database with the other items needed.

- [Catalog of GTFS Realtime sources](http://mobilitydatabase.org/wiki/Item:Q90051)
- [GTFS Realtime data format](http://mobilitydatabase.org/wiki/Item:Q90052)
- [Protobuf](http://mobilitydatabase.org/wiki/Item:Q90053)
