### ISSUE TITLE
Get usage data on OMD database for the following questions

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-database-interface#333]
- What has usage from January 2020 to end of December 2020 been for

Downloads vs. API vs. system status 

- Who were the power users (say top 20) for downloads during this time? (and their contact info)
- Who were the power users for the API during this time? (and their contact info)
- How many downloads are associated with a GitHub user vs. ones that are not?
- How many API requests occurred for each endpoint during this period?
- Is there any way for us to see which feeds were the most downloaded?
- List of all users' contact info who have used OMD over the past year that we know of

**Comment by maximearmstrong** [comment]
Answers shared with @emmambd via an internal document.
